name: SARIF check

on:
  pull_request:
    types: [opened, synchronize]


jobs:
  sarif-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Check for SARIF report
        continue-on-error: true
        run: |
          if curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "${{ github.event.pull_request.url }}/files" | jq -r '.[].filename' | grep -q 'semgrep-python-results'; then
            echo "SARIF file found."
            echo "sarif_found=true" >> $GITHUB_ENV
          else
            echo "SARIF file not found."
            echo "sarif_found=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Add SARIF Reminder
        if: env.sarif_found == 'false'
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          COMMENT_BODY="**This PR is missing a SARIF report.** Please refer to our local SAST scanning [guidelines](https://github.com/kmitsch/precommit-sarif/blob/main/README.md#sast-scanning-guidelines). We also provide a [walk-through](https://github.com/kmitsch/precommit-sarif/blob/main/README.md#setting-up-semgrep-for-pre-commit) for setting up a pre-commit hook on your local workstation."
          curl -s -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"$COMMENT_BODY\"}" \
            "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments"
